development:
  adapter: postgresql
  database: kaizenstorm_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: kaizenstorm_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kaizenstorm_production
  pool: 5
  timeout: 5000


