defaults: &defaults
  app_name: ENV['APP_NAME']
  from_email: ENV['FROM_EMAIL']
  base_domain: ENV['BASE_DOMAIN']

  gateway: ENV['GATEWAY'] # Change this to stripe to use stripe
  credentials:
    gateway:
      :login: ENV['STRIPE_SECRET'] # stripe secret key goes here
      :password: ENV['GATEWAY_PASSWORD'] # leave blank for stripe
    stripe_publishable_key: ENV['STRIPE_KEY']