defaults: &defaults
  app_name: KaizenStorm
  from_email: support@kaizenstorm.com
  base_domain: kaizenstorm.com

  gateway: bogus # Change this to stripe to use stripe
  credentials:
    gateway:
      :login: demo # stripe secret key goes here
      :password: password # leave blank for stripe
    stripe_publishable_key: # use this to send cc info directly to stripe via javascript

development:
  <<: *defaults
  base_domain: subscriptions.dev # Edit /etc/hosts to add subscriptions.dev, test.subscriptions.dev, etc., or use Pow: http://pow.cx

test:
  <<: *defaults

production:
  <<: *defaults
  credentials:
    gateway:
      :login: demo
      :password: password